name: 'Jira Changelog'
description: 'Generates a changelog message by looking at Jira issue keys ([DEV-123]) in commit messages.'
inputs:
    jira_host:
        description: 'Root host of your JIRA installation without protocol. // (i.e "yourapp.atlassian.net")'
        default: 'https://atlassian.net'
        required: true
    jira_email:
        description: 'Email address of the user to login with'
        default: 'e@email.com'
        required: true
    jira_token:
        description: 'Auth token of the user to login with'
        default: 'knmD98cbfsd£jnfjnH?KHKH'
        required: true
    jira_base_url:
        description: 'Jira base web URL for changelog message entries'
        default: 'https://atlassian.net'
        required: false
    jira_ticket_id_pattern:
        description: 'Regex used to match the issue ticket key'
        default: /\[([A-Z]+\-[0-9]+)\]/i
        required: false
    source_control_range_from:
        description: 'Starting branch to get range of commits'
        default: 'develop'
        required: false
    source_control_range_to:
        description: 'Ending branch to get range of commits'
        default: 'master'
        required: false
    approval_statuses:
        description: 'Comma separated list of issue statuses treated as approved'
        default: 'Done,Closed,Accepted'
        required: false
    exclude_issue_types:
        description: 'Comma separated list of issue types to exclude from changelog'
        default: 'Sub-task'
        required: false
    include_pending_approval_section:
        description: 'Boolean flag indicating whether to include or exclude `Pending Approval` section'
        default: 'true'
        required: false
outputs:
    changelog_message:
        description: 'Generated changelog entry'
runs:
    using: 'node12'
    main: 'index.js'